version: '3.7'
services:
    node: 
        build:
            context: ./server
            dockerfile: ./image/Dockerfile
        working_dir: /src/app
        volumes:
            - ./server/package.json:/src/app/package.json
            - ./server/bin:/src/app/bin
        expose:
            - "5000"
        ports:
            - "5000:5000"
        depends_on:
            - mongo
        env_file:
            - ./server/.env
        command: "nodemon --inspect=0.0.0.0:8080 --watch bin"
    mongo:
        image: mongo
        volumes:
            - ./db:/data/db
        ports:
            - "27017:27017"